deploy:
  needs: build-and-push
  runs-on: self-hosted

  steps:
    - name: Pull latest image
      shell: powershell
      run: |
        docker pull vikaspatel11/spring-boot-app:latest

    - name: Stop old container
      shell: powershell
      run: |
        docker stop spring-boot-app-container 2>$null
        docker rm spring-boot-app-container 2>$null

    - name: Run new container
      shell: powershell
      run: |
        docker run -d `
          --name spring-boot-app-container `
          -p 8080:8080 `
          vikaspatel11/spring-boot-app:latest